# Generated by Django 4.2.5 on 2023-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_manage_article',
            field=models.BooleanField(default=False, verbose_name='can manage article'),
        ),
    ]
