# Generated by Django 4.2.5 on 2023-09-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catgory',
            new_name='category',
        ),
    ]
